### ISSUE TITLE
Memory leak in Tree destructor

### ISSUE THREAD

**Issue by SiyuanQi** [RoboJackets/rrt#57]
In the [destructor](https://github.com/RoboJackets/rrt/blob/master/src/rrt/Tree.hpp#L121) of the Tree class, seems that a parameter should be passed to avoid memory leak:
```cpp
    virtual ~Tree() { reset(true); }
```

**Comment by ashaw596** [comment]
Nice catch! I think your're right. @justbuchanan @joshhting  Is there any particular reason _nodes its a vector of Node* instead of just Node?

**Comment by jgkamat** [comment]
I think that it needs to be a Node* because otherwise we'll need to store all the nodes on the stack (or have a pointer to a vector). Does vector automagically put things in the heap for you? I'm not sure.

@SiyuanQi Thanks! that definetly looks like a  problem. If you want, you can submit a PR if you're sure about it, you did find it after all :smile: 

@joshhting can you verify that this is actually a memory leak? It looks like it is to me at a first glance (I don't have enough time to look at it too closely :cry:)

**Comment by ashaw596** [comment]
I mean vector allocates everything on the heap anyways so that shouldn't be an issue. Why don't we just change it to a normal vector? Is there any where ownership stuff thats going on?

**Comment by jgkamat** [comment]
I don't think there is, but josh or justin probably would have a better idea. In that case we might want to refactor that (but after we merge the PR's justin is submitting).

**Comment by justbuchanan** [comment]
Yep, that's a memory leak! Good find. @ashaw596, you're right - it would probably be better to store the nodes directly in the vector rather than via pointer. It would be more efficient and a little simpler too.
