### ISSUE TITLE
Repeatable experiments

### ISSUE THREAD

**Issue by steenax86** [RoboJackets/rrt#83]
Is there a way to set a seed in the code such that the number of steps (or trees) stay the same for a fixed obstacle setup?

Thanks,
Steena

**Comment by jgkamat** [comment]
Hi @steenax86!

I don't think that there is a way to do this currently, but I think that this is a very useful feature to have!

Right now, I think the best way to solve this would be https://github.com/RoboJackets/rrt/issues/25, after which we could add a random seed parameter to the RRT gui, and have reproducable RRT runs that way (by supplying a seed).

@joshhting, do you have enough free time to take a look at https://github.com/RoboJackets/rrt/issues/25 (or find someone to delegate it to)? It's had a lot of back/forth for a while with no progress, so it would be nice to have someone step up :). Unfortunately I have way too much to do to try and take a look at this.

I think that this could be a bit of work, I heard from Jeremy that the random libraries we use are a little bit weird, so that might need to be changed too.

**Comment by steenax86** [comment]
Hi @jgkamat 
Thank you very much! This will be very useful to have. I tried using srand(1) to no effect. I suspect the fix will need a deeper investigation. I look forward to the official fix!

**Comment by JNeiger** [comment]
If you are cool with a quick and dirty fix, add the lines
```
unsigned short seed[3] - {0, 0, 0};
seed48(seed);
```
into the `reset` function of the `Tree` class in the file `Tree.hpp`.

[Here's a gist](https://gist.github.com/JNeiger/37fed8473f6edcf7ab65e4ba213add17) of my current file.

**Comment by steenax86** [comment]
@JNeiger Excellent! Thank you very much! This fix works for me!

**Comment by jgkamat** [comment]
It's still a good idea to implement this properly, but the above snippet should help with the implementation (if we decide to keep the same random number generation method we do right now). 

Glad it worked for you though! :smile:
