### ISSUE TITLE
Modifying your open code

### ISSUE THREAD

**Issue by LZDSJTU** [RoboJackets/rrt#90]
Hi~I Modify your open code and open it in github. But I do not know if I do some wrong that violate the Apache License v2.0 license. So I want you to check it.
If I do something wrong, you can tell me and I will change it.

I sent an e-mail here(hello@robojackets.org) 

If you see this email, hope you can reply me to let me know if I do something wrong or I need to add somthing as I want to open the modified code.

Thank you very much!

**Comment by joshhting** [comment]
@jgkamat I feel like you understand licenses better, but as far as I'm aware, the [Apache License](https://choosealicense.com/licenses/apache-2.0/) requires that a copy of the license be included as well as changes to the code be documented

**Comment by jgkamat** [comment]
Josh Ting writes:

> @jgkamat I feel like you understand licenses better, but as far as I'm
> aware, the Apache License requires that a copy of the license be included as
> well as changes to the code be documented

Yup, that seems correct. I took a look at what was published
(https://github.com/LZDSJTU/RRT-path-planning-with-OpenGL-simulator) and it
looks really cool to me! I'll try to run it when I get some free time :).


>> If you see this email, hope you can reply me to let me know if I do
>> something wrong or I need to add somthing as I want to open the modified
>> code.

From a legal perspective you're doing everything perfectly! However, if you
have some patches that you made while using the RRT I would love it if you
could take a bit of time to contribute them back (so everyone using this
library gets them for free in the future)!

It looks like you are just using our RRT at the moment, so that doesn't make
sense at this point (I think). However, if you ever find any bugs or add any
features to the RRT, we would love to have them contributed back (at your
discretion, of course) :).


Lastly, thanks for using our library, one of the reasons we split it off from
the rest of our software was to make it easier for others to use, and I'm
happy to see that decision is paying off! If you have any questions about
using it, just let us know and we'll try to find someone to help you out.

CC: @justbuchanan (because he's probably interested to see what you made!)

**Comment by justbuchanan** [comment]
Cool project! Thanks for letting us know, it's always nice to see other people making use of our code :)

As Jay said, it looks like you're doing everything fine - you mentioned in your readme that it was based on this project and you included a copy of the license.

Hack on!

**Comment by LZDSJTU** [comment]
Thank you very much for your replying.

----- 原始邮件 -----
发件人: "Justin Buchanan" <notifications@github.com>
收件人: "RoboJackets/rrt" <rrt@noreply.github.com>
抄送: "LZDSJTU" <LZD950512@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期二, 2018年 7 月 10日 上午 10:13:03
主题: Re: [RoboJackets/rrt] Modifying your open code (#90)

Cool project! Thanks for letting us know, it's always nice to see other people making use of our code :)

As Jay said, it looks like you're doing everything fine - you mentioned in your readme that it was based on this project and you included a copy of the license.

Hack on!

**Comment by LZDSJTU** [comment]
Thank you very much for your replying.

I will add the changes to the code in the license later.

----- 原始邮件 -----
发件人: "Jay Kamat" <notifications@github.com>
收件人: "RoboJackets/rrt" <rrt@noreply.github.com>
抄送: "LZDSJTU" <LZD950512@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期五, 2018年 7 月 06日 下午 2:39:57
主题: Re: [RoboJackets/rrt] Modifying your open code (#90)

Josh Ting writes:

> @jgkamat I feel like you understand licenses better, but as far as I'm
> aware, the Apache License requires that a copy of the license be included as
> well as changes to the code be documented

Yup, that seems correct. I took a look at what was published
(https://github.com/LZDSJTU/RRT-path-planning-with-OpenGL-simulator) and it
looks really cool to me! I'll try to run it when I get some free time :).


>> If you see this email, hope you can reply me to let me know if I do
>> something wrong or I need to add somthing as I want to open the modified
>> code.

From a legal perspective you're doing everything perfectly! However, if you
have some patches that you made while using the RRT I would love it if you
could take a bit of time to contribute them back (so everyone using this
library gets them for free in the future)!

It looks like you are just using our RRT at the moment, so that doesn't make
sense at this point (I think). However, if you ever find any bugs or add any
features to the RRT, we would love to have them contributed back (at your
discretion, of course) :).


Lastly, thanks for using our library, one of the reasons we split it off from
the rest of our software was to make it easier for others to use, and I'm
happy to see that decision is paying off! If you have any questions about
using it, just let us know and we'll try to find someone to help you out.

CC: @justbuchanan (because he's probably interested to see what you made!)
